### ISSUE TITLE
你好，帮我编译一个R4A固件好吗？

### ISSUE THREAD

**Issue by ghost** [JohyC/Actions_lede#4]
需要SSRPLUS和openclash，
我很快会把R4A的flash换成32M或者64M的，想试试。

谢谢

**Comment by ghost** [comment]
还有，我的actions功能被禁用了，以前我没用过github，不懂。不知道为什么被封，糊涂啊。

**Comment by JohyC** [comment]
> 需要SSRPLUS和openclash，
> 我很快会把R4A的flash换成32M或者64M的，想试试。
> 
> 谢谢

魔改flash只能你自己编译固件。。。flash布局分区不合适，编译好固件也没法用。
actions被封就神奇了，我也不知道怎么解决，没遇过。。。

**Comment by ghost** [comment]
可能是fork太高调了，公开的嘛，所以，我要把所有库都删除了，不知道怎么改成私有。

**Comment by JohyC** [comment]
> 可能是fork太高调了，公开的嘛，所以，我要把所有库都删除了，不知道怎么改成私有。

settings 页面最下方有个 Change visibility 选项；

**Comment by jihesong** [comment]
算了，干脆把账户删除了，重新注册了，那个R4A完了，烫下闪存时候，发现周围有几个很小的电阻或者是电容，实在是太小了，比0201小得多，所以所以顺便烫下个焊盘，然后，根本没法人焊，除非有个大号放大镜，而且黑色的电路板，想飞线都看不清，没R4A的事了，我服了黑色PCB+超小封装的电阻，随便一块fr4都比小米的结实。本来我想焊下来把数据读出来，复制到大闪存上，焊上大闪存，万无一失，大不了，用不了16M以外的容量，老天不给力。

**Comment by JohyC** [comment]
> 算了，干脆把账户删除了，重新注册了，那个R4A完了，烫下闪存时候，发现周围有几个很小的电阻或者是电容，实在是太小了，比0201小得多，所以所以顺便烫下个焊盘，然后，根本没法人焊，除非有个大号放大镜，而且黑色的电路板，想飞线都看不清，没R4A的事了，我服了黑色PCB+超小封装的电阻，随便一块fr4都比小米的结实。本来我想焊下来把数据读出来，复制到大闪存上，焊上大闪存，万无一失，大不了，用不了16M以外的容量，老天不给力。

有个显微镜就方便了，以前修手机时显微镜用的顺手。
