### ISSUE TITLE
求助: 从双系统刷回官方单系统方法

### ISSUE THREAD

**Issue by charmingYouYou** [JohyC/Actions_lede#5]
您好, 从恩山来的, 按照教程ax3600刷了双系统, 但因openwrt不太稳定, 想用回官方固件 + shellClash等相关插件
目前问题是官方固件分区很小, 空间不足导致无法安装所需相关插件, 所以想问下可否从双系统刷回单系统的方法, 好有足够的空间来安装插件
当然如有更好的方法最好不过, 感谢!

**Comment by JohyC** [comment]
> 您好, 从恩山来的, 按照教程ax3600刷了双系统, 但因openwrt不太稳定, 想用回官方固件 + shellClash等相关插件 目前问题是官方固件分区很小, 空间不足导致无法安装所需相关插件, 所以想问下可否从双系统刷回单系统的方法, 好有足够的空间来安装插件 当然如有更好的方法最好不过, 感谢!

这个问题难住我了。。我从来没想过需要刷回去的。。。

**Comment by charmingYouYou** [comment]
> > 您好, 从恩山来的, 按照教程ax3600刷了双系统, 但因openwrt不太稳定, 想用回官方固件 + shellClash等相关插件 目前问题是官方固件分区很小, 空间不足导致无法安装所需相关插件, 所以想问下可否从双系统刷回单系统的方法, 好有足够的空间来安装插件 当然如有更好的方法最好不过, 感谢!
> 
> 这个问题难住我了。。我从来没想过需要刷回去的。。。

好的, 感谢, 我在论坛再看看吧
