### ISSUE TITLE
AX3600 xiaomimtd12.bin固件WEB密码

### ISSUE THREAD

**Issue by panda901201** [JohyC/Actions_lede#9]
您好，请问新的xiaomimtd12.bin固件登入帐号密码是什么呢? root, boos, admin跟password的组合都试过了，先谢谢了！

**Comment by JohyC** [comment]
就是 boos 呀！密码不对吗？？？

**Comment by panda901201** [comment]
https://www.aliyundrive.com/s/VPs34DCj85C

**Comment by JohyC** [comment]
> [aliyundrive.com/s/VPs34DCj85C](https://www.aliyundrive.com/s/VPs34DCj85C)

你这个界面是 tp link 路由器呀！ 不是 openwrt。 你确定你刷入固件了吗？
openwrt 登录界面是这样的！
![image](https://user-images.githubusercontent.com/38210128/172169747-f0d73fb8-7fd2-4abd-b943-46a0a7e6b85f.png)

**Comment by panda901201** [comment]
我看恩山也有人遇到这个问题，在帖子下留言，是上Onedrive里的Xiaomi AX3600里"刷机固件包及其QSDK包"里的xiaomimtd12.bin

**Comment by panda901201** [comment]
<img width="864" alt="截屏2022-06-06 21 29 18" src="https://user-images.githubusercontent.com/7693844/172170235-eb943d87-3acc-4f6b-b417-c93999d8f8f3.png">

**Comment by panda901201** [comment]
我是做到第四步重启之后进到192.168.1.1 然后出现这个，还是我现在能用reset重新来? 会不会变砖

**Comment by JohyC** [comment]
你。。。你仔细看看你路由器重启了吗？你路由器重启之后分配的IP网关是什么。。
你这 访问192.168.1.1 是进入到另外一个路由器中去了。
你仔细看看教程，多思考思考再上手。（你得弄明白你到底在做什么！！！）

另外你现在这个个问题，我无法回答。。只能给你提供思路。
你把电脑和路由多余的网线去掉，只留下电脑连接路由LAN口的网线。然后再尝试。

**Comment by panda901201** [comment]
喔喔！！！！ 唉，我真白痴！忘了拔另一台的网线，明天到公司试一下，谢谢大大，不好意思阿！！ 谢谢您这么热心积极的协助！
